CREATE VIEW v_SHOWS AS
		SELECT ShowTime,ShowTimeID,
			CASE 
				WHEN ShowTimeID BETWEEN 400 AND 432 THEN 'EARLYBIRDS'
				WHEN ShowTimeID BETWEEN 433 AND 505 THEN 'BIRDSOFDAY'
				WHEN ShowTimeID BETWEEN 506 AND 552 THEN 'BIRDSOFEVE'
				WHEN ShowTimeID BETWEEN 553 AND 587 THEN 'BIRDSOFNIGHT'
				ELSE 'LAZYBIRD'
			END AS "SHOWNAME"
		FROM SHOWTIME;

--SELECT * FROM v_SHOWS;

--DROP VIEW V_SHOWS;